-- Dražby nehnuteľností SK – schéma pre Supabase (Postgres + PostGIS)
-- Zodpovedá SQLite schéme v scrapers/drazby/db.py. Dáta sa prelievajú cez `python -m drazby pgsync`.

create extension if not exists postgis;

create table if not exists auctions (
  id bigint primary key,
  group_key text unique not null,
  kind text not null check (kind in ('dobrovolna', 'exekucna', 'danova')),
  status text not null default 'pripravovana'
    check (status in ('pripravovana', 'odrocena', 'prebehla', 'zrusena', 'zmarena', 'neplatna')),
  auction_number text,
  auctioneer_name text,
  auctioneer_ico text,
  proposer text,
  notary text,
  auction_at timestamp,
  venue text,
  round int,
  min_bid numeric(14, 2),
  min_increment numeric(14, 2),
  deposit numeric(14, 2),
  appraised_value numeric(14, 2),
  highest_bid numeric(14, 2),
  sold boolean,
  inspection text,
  title text,
  description text,
  reason text,
  property_type text,
  kraj text,
  okres text,
  obec text,
  ku text,
  geom geography(Point, 4326),
  geo_precision text,
  sources jsonb not null default '[]',
  first_seen timestamptz not null,
  last_seen timestamptz not null,
  updated_at timestamptz not null,
  last_notice_at date
);
create index if not exists auctions_date_idx on auctions (auction_at);
create index if not exists auctions_geom_idx on auctions using gist (geom);
create index if not exists auctions_filters_idx on auctions (kraj, okres, property_type, kind, status);

create table if not exists notices (
  id bigint primary key,
  source text not null check (source in ('ov', 'ncrd')),
  source_id text not null,
  auction_id bigint references auctions (id) on delete set null,
  kind text,
  notice_type text,
  source_url text,
  source_label text,
  published_at date,
  auction_at timestamp,
  payload jsonb not null,
  content_hash text not null,
  first_seen timestamptz not null,
  last_seen timestamptz not null,
  unique (source, source_id)
);
create index if not exists notices_auction_idx on notices (auction_id);

create table if not exists properties (
  id bigint primary key,
  auction_id bigint not null references auctions (id) on delete cascade,
  idx int not null,
  type text,
  kraj text,
  okres text,
  obec text,
  obec_code text,
  ku text,
  lv jsonb not null default '[]',
  parcels jsonb not null default '[]',
  supisne_cislo jsonb not null default '[]',
  area_m2 numeric(12, 2),
  address text,
  share text,
  point geography(Point, 4326),
  geom geometry(Geometry, 4326),          -- polygón parcely
  geo_source text,
  unique (auction_id, idx)
);
create index if not exists properties_geom_idx on properties using gist (geom);

create table if not exists auction_history (
  id bigint primary key,
  auction_id bigint not null references auctions (id) on delete cascade,
  changed_at timestamptz not null,
  field text not null,
  old_value text,
  new_value text,
  notice_id bigint references notices (id) on delete set null
);
create index if not exists history_auction_idx on auction_history (auction_id);

create table if not exists scrape_runs (
  id bigint primary key,
  source text not null,
  started_at timestamptz not null,
  finished_at timestamptz,
  fetched int default 0,
  new_notices int default 0,
  changed_notices int default 0,
  new_auctions int default 0,
  errors int default 0,
  message text
);

-- uložené hľadania (notifikácie e-mailom)
create table if not exists saved_searches (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  filters jsonb not null,
  created_at timestamptz not null default now(),
  last_notified_at timestamptz,
  active boolean not null default true
);
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  search_id bigint not null references saved_searches (id) on delete cascade,
  auction_id bigint not null references auctions (id) on delete cascade,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (search_id, auction_id)
);

-- Verejné čítanie (anon kľúč vo frontende), zápis len cez service role (scraper).
alter table auctions enable row level security;
alter table notices enable row level security;
alter table properties enable row level security;
alter table auction_history enable row level security;
alter table scrape_runs enable row level security;
alter table saved_searches enable row level security;
alter table notifications enable row level security;

create policy "verejne citanie" on auctions for select using (true);
create policy "verejne citanie" on properties for select using (true);
create policy "verejne citanie" on auction_history for select using (true);
create policy "verejne citanie" on notices for select using (true);
-- saved_searches: žiadna verejná politika – e-maily sú osobné údaje, prístup len cez service role.

-- Pohľad pre mapu (kompaktný ako auctions.json)
create or replace view auctions_map as
select
  id, kind, status, property_type, title, kraj, okres, obec, ku, auction_at, round,
  min_bid, appraised_value, highest_bid,
  st_y(geom::geometry) as lat, st_x(geom::geometry) as lng, geo_precision, auctioneer_name, first_seen
from auctions;
